
# management:
#     endpoints:
#         enabled-by-default: true
#         web:
#             exposure:
#                 include: "*"

logging:
    level:
        org.springframework.web: debug
    file.name: complaintform.log